### ISSUE TITLE
react-native-async-storage/async-storage

### ISSUE THREAD

**Issue by simoncar** [johnny-quesada-developer/react-native-global-state-hooks#1]
Great library, thanks, just want I was looking for to move from redux

any plans to move the dependency from 
@react-native-community/async-storage
to
react-native-async-storage/async-storage

**Comment by johnny-quesada-developer** [comment]
Hi man, I'm so glad for those words... thank you so much, I'm yeah, I'll be committing that change between today and tomorrow morning.

**Comment by johnny-quesada-developer** [comment]
@simoncar  it's done, I didn't know the other one was deprecated. thanks. Version 1.1.1 has the update.
