### ISSUE TITLE
Multiple Persisted stores 

### ISSUE THREAD

**Issue by simoncar** [johnny-quesada-developer/react-native-global-state-hooks#2]
When performing multiple setters on different persisted stores, all setters update state but only the last setter is persisted into async-storage.

I created a minimum example demonstrating this.  Maybe i'm doing it wrong, if so apologies.

https://github.com/simoncar/testRNGSH
(open demo, press button 1 or 2 then reload and only last setter is persisted)

**Comment by johnny-quesada-developer** [comment]
Thanks a lot, @simoncar, there was a little defect with an internal awaiter... I solved it a tested it into your code example now is working as expected.

please just update to 1.1.2
