### ISSUE TITLE
Actions: it is possible to call a store action from another action ?

### ISSUE THREAD

**Issue by jacargentina** [johnny-quesada-developer/react-native-global-state-hooks#5]
@johnny-quesada-developer 
I have a case where I need to call an action from another one. Is that even possible?

**Comment by johnny-quesada-developer** [comment]
> @johnny-quesada-developer 
> 
> I have a case where I need to call an action from another one. Is that even possible?

Hi @jacargentina , it is possible , now I'm far from the computer but once back in the office Ill help you with an example. Regards

**Comment by victoriasyluma** [comment]
> @johnny-quesada-developer 
> 
> I have a case where I need to call an action from another one. Is that even possible?

Hi, @jacargentina it is possible! 
To call one action inside another one you should use "this" -
keyword inside the activation.

You could also get the action from decoupled hook and use them in class components.

**Comment by johnny-quesada-developer** [comment]
Hi @jacargentina , 

In response to your question about calling a store action from another one, I wanted to let you know that, as @victoriasyluma mentioned, it is indeed possible. Here's an example

```ts
 const countStore = new GlobalStore(0, null, {
    log(message: string) {
      return (): void => console.log(message);
    },

    increase(increase: number = 1) {
      return ({ setState, getState }: StoreTools<number>) => {
        setState((state) => state + increase);

        /** through the decoupled actions you can use them directly in any place, this actions are not hooks
        * but they are connected to the state an they will update all the subscribers */
        actions.log('increase');

        /* You can also directly use the "this" keyword,
        * this also will work, the only trouble is that typescript will not recognise the action types
        * and "log" will be an "any" type... So Ill recommend you to use use the decoupled actions */
        this.log('increase');

        return getState();
      };
    },

    decrease(decrease: number = 1) {
      return ({ setState, getState }: StoreTools<number>) => {
        setState((state) => state - decrease);

        this.log('decrease');

        return getState();
      };
    },
  } as const);

  const [_, actions] = countStore.getHookDecoupled();
```

Thank you for using the library, and please let me know if you have any additional questions.

Regards .

**Comment by jacargentina** [comment]
Thanks a lot!
