### ISSUE TITLE
3.0.7 breaks app

### ISSUE THREAD

**Issue by jacargentina** [johnny-quesada-developer/react-native-global-state-hooks#6]
Also I can't see the changes pushed to upstream.

**Comment by johnny-quesada-developer** [comment]
> Also I can't see the changes pushed to upstream.

Hi @jacargentina , can you please provide the error message? I'll review it immediately.

Thanks

**Comment by jacargentina** [comment]
I’m migrating to zustand ; thanks!

**Comment by johnny-quesada-developer** [comment]
> I’m migrating to zustand ; thanks!

Hi @jacargentina 

I understand. I sincerely apologize for the inconvenience the regression caused. 

Thank you very much for giving this library a try and for providing your valuable feedback.

Regards,
